# Read the Docs configuration
# Reference: https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

mkdocs:
  configuration: mkdocs.yml
