# Read the Docs configuration
# Reference: https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install .[dev]

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
