"""
GitHub Copilot proxy management using subprocess.

This module manages a copilot-api proxy server as a subprocess,
eliminating the need for Docker.
"""

import subprocess
import time
import os
import atexit
from typing import Optional
import requests


class CopilotProxyManager:
    """Manages copilot-api proxy server as a subprocess."""

    def __init__(
        self,
        github_token: Optional[str] = None,
        rate_limit: int = 30,
        use_wait: bool = True,
        port: Optional[int] = None,
        verbose: bool = True,
    ):
        """
        Initialize Copilot proxy manager.

        Args:
            github_token: GitHub token with copilot scope (or from env/1Password)
            rate_limit: Minimum seconds between requests (default: 30)
            use_wait: Wait during cooldown instead of rejecting (default: True)
            port: Port to run proxy on (default: None, uses copilot-api default 4141)
            verbose: Enable verbose logging (default: True)
        """
        self.github_token = github_token or self._get_github_token()
        self.rate_limit = rate_limit
        self.use_wait = use_wait
        self.port = port
        self.verbose = verbose
        self.process: Optional[subprocess.Popen] = None
        self._started = False

        # Register cleanup on exit
        atexit.register(self.stop)

    def _get_github_token(self) -> Optional[str]:
        """Get GitHub token from environment or 1Password."""
        # Try environment variable first
        token = os.getenv("GITHUB_TOKEN")
        if token:
            return token

        # Try 1Password
        try:
            from .secrets import SecretManager

            token = SecretManager.get_github_token()
            if token:
                return token
        except ImportError:
            pass

        return None

    def is_installed(self) -> bool:
        """Check if copilot-api is installed globally."""
        try:
            result = subprocess.run(
                ["npx", "copilot-api@latest", "--version"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            return result.returncode == 0
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return False

    def install(self) -> bool:
        """
        Install copilot-api globally using npx.

        Returns:
            True if installation successful
        """
        print("Installing copilot-api...")
        try:
            result = subprocess.run(
                ["npm", "install", "-g", "copilot-api@latest"],
                capture_output=True,
                text=True,
                timeout=120,
            )

            if result.returncode == 0:
                print("✓ copilot-api installed successfully")
                return True
            else:
                print(f"✗ Installation failed: {result.stderr}")
                return False

        except subprocess.TimeoutExpired:
            print("✗ Installation timed out")
            return False
        except FileNotFoundError:
            print("✗ npm not found. Please install Node.js first.")
            return False

    def start(self, wait_for_ready: bool = True, timeout: float = 30.0) -> bool:
        """
        Start the copilot-api proxy server.

        Args:
            wait_for_ready: Wait for server to be ready before returning
            timeout: Seconds to wait for server readiness

        Returns:
            True if server started successfully
        """
        if self._started:
            print("Proxy already running")
            return True

        if not self.github_token:
            raise ValueError(
                "GitHub Copilot token required.\n"
                "\n"
                "To generate a Copilot token:\n"
                "  1. Run: npx copilot-api@latest auth\n"
                "  2. Follow the prompts to authenticate\n"
                "  3. Save the token (starts with 'ghu_') to GITHUB_TOKEN env var or 1Password\n"
                "\n"
                "Note: Regular GitHub PATs (ghp_*) are NOT supported!"
            )

        # Validate token format
        if not self.github_token.startswith('ghu_'):
            raise ValueError(
                f"Invalid GitHub Copilot token format.\n"
                "\n"
                f"Token starts with: {self.github_token[:4]}***\n"
                f"Expected format: ghu_***\n"
                "\n"
                "Your token appears to be a GitHub PAT (ghp_*), which is NOT supported.\n"
                "You must use a Copilot-specific token generated by:\n"
                "  npx copilot-api@latest auth\n"
            )

        # Build command
        cmd = [
            "npx", "copilot-api@latest", "start",
            "--rate-limit", str(self.rate_limit),
            "--github-token", self.github_token
        ]

        # Only add port if specified (otherwise use copilot-api default 4141)
        if self.port is not None:
            cmd.extend(["--port", str(self.port)])

        if self.use_wait:
            cmd.append("--wait")

        if self.verbose:
            cmd.append("--verbose")

        # Use current environment (no custom vars needed)
        env = os.environ.copy()

        port_display = self.port if self.port is not None else "4141 (default)"
        print(f"Starting copilot-api proxy on port {port_display}...")
        print(f"  Rate limit: {self.rate_limit}s")
        print(f"  Wait mode: {self.use_wait}")
        print(f"  Verbose: {self.verbose}")

        try:
            # Start process
            self.process = subprocess.Popen(
                cmd,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            self._started = True

            if wait_for_ready:
                if self.wait_for_ready(timeout=timeout):
                    port_display = self.port if self.port is not None else 4141
                    print(f"✓ Proxy server ready at http://localhost:{port_display}")
                    return True
                else:
                    print("✗ Proxy failed to start within timeout")
                    self.stop()
                    return False

            return True

        except FileNotFoundError:
            print("✗ npx not found. Please install Node.js first.")
            return False
        except Exception as e:
            print(f"✗ Failed to start proxy: {e}")
            return False

    def wait_for_ready(self, timeout: float = 30.0) -> bool:
        """
        Wait for proxy server to be ready.

        Args:
            timeout: Maximum seconds to wait

        Returns:
            True if server becomes ready
        """
        start_time = time.time()
        port = self.port if self.port is not None else 4141
        health_url = f"http://localhost:{port}/"

        while time.time() - start_time < timeout:
            try:
                response = requests.get(health_url, timeout=1.0)
                if response.status_code == 200:
                    return True
            except requests.exceptions.RequestException:
                pass

            # Check if process died
            if self.process and self.process.poll() is not None:
                print(f"✗ Proxy process exited with code {self.process.returncode}")
                stderr = self.process.stderr.read() if self.process.stderr else ""
                if stderr:
                    print(f"  Error output: {stderr}")
                return False

            time.sleep(0.5)

        return False

    def stop(self):
        """Stop the proxy server."""
        if not self._started or not self.process:
            return

        print("Stopping copilot-api proxy...")

        try:
            # Try graceful shutdown first
            self.process.terminate()

            # Wait up to 5 seconds for graceful shutdown
            try:
                self.process.wait(timeout=5.0)
                print("✓ Proxy stopped gracefully")
            except subprocess.TimeoutExpired:
                # Force kill if still running
                self.process.kill()
                self.process.wait()
                print("✓ Proxy forcefully stopped")

        except Exception as e:
            print(f"Warning: Error stopping proxy: {e}")

        finally:
            self.process = None
            self._started = False

    def is_running(self) -> bool:
        """Check if proxy server is running and responsive."""
        if not self._started or not self.process:
            return False

        # Check if process is alive
        if self.process.poll() is not None:
            self._started = False
            return False

        # Check if server responds
        try:
            port = self.port if self.port is not None else 4141
            response = requests.get(f"http://localhost:{port}/health", timeout=2.0)
            return response.status_code == 200
        except requests.exceptions.RequestException:
            return False

    def get_base_url(self) -> str:
        """Get the base URL for the proxy server."""
        port = self.port if self.port is not None else 4141
        return f"http://localhost:{port}/v1"

    def __enter__(self):
        """Context manager entry."""
        self.start()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.stop()


# Singleton instance for easy access
_proxy_instance: Optional[CopilotProxyManager] = None


def get_proxy_manager(
    github_token: Optional[str] = None,
    rate_limit: int = 30,
    use_wait: bool = True,
    port: Optional[int] = None,
    verbose: bool = True,
) -> CopilotProxyManager:
    """
    Get or create the global proxy manager instance.

    Args:
        github_token: GitHub token (optional if in env/1Password)
        rate_limit: Minimum seconds between requests
        use_wait: Wait during cooldown instead of rejecting
        port: Port to run on (default: None, uses copilot-api default 4141)
        verbose: Enable verbose logging

    Returns:
        CopilotProxyManager instance
    """
    global _proxy_instance

    if _proxy_instance is None:
        _proxy_instance = CopilotProxyManager(
            github_token=github_token,
            rate_limit=rate_limit,
            use_wait=use_wait,
            port=port,
            verbose=verbose,
        )

    return _proxy_instance


def start_proxy(
    github_token: Optional[str] = None,
    rate_limit: int = 30,
    use_wait: bool = True,
    wait_for_ready: bool = True,
) -> bool:
    """
    Start the copilot-api proxy server (convenience function).

    Args:
        github_token: GitHub token (optional if in env/1Password)
        rate_limit: Minimum seconds between requests
        use_wait: Wait during cooldown instead of rejecting
        wait_for_ready: Wait for server to be ready

    Returns:
        True if server started successfully
    """
    manager = get_proxy_manager(github_token=github_token, rate_limit=rate_limit, use_wait=use_wait)
    return manager.start(wait_for_ready=wait_for_ready)


def stop_proxy():
    """Stop the copilot-api proxy server (convenience function)."""
    global _proxy_instance
    if _proxy_instance:
        _proxy_instance.stop()
        _proxy_instance = None


def is_proxy_running() -> bool:
    """Check if proxy is running (convenience function)."""
    if _proxy_instance:
        return _proxy_instance.is_running()
    return False
